name: Publish to NPM

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # Install dependencies
      - run: yarn

      # Set version using the tag name
      - name: Set package version from tag
        run: yarn version --new-version ${{ github.ref_name }}

      # Publish to NPM using Yarn
      - run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
